In [1]:
import numpy as np


In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [3]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [6]:
#two dimention
a = np.array([[1,2,3],
              [4,5,6]])

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [9]:
np.concatenate([a,a],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])