In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
a[0:3]

array([20, 21, 22])

In [4]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [5]:
a[1::2]

array([21, 23, 25, 27, 29])

In [6]:
#slice process in two dimention

In [7]:
m = np.random.randint(10,size = (5,5))

In [8]:
m

array([[5, 7, 3, 5, 0],
       [6, 9, 2, 5, 0],
       [3, 8, 6, 8, 7],
       [8, 5, 5, 4, 2],
       [5, 2, 4, 4, 6]])

In [10]:
m[:,0]

array([5, 6, 3, 8, 5])

In [11]:
m[3,:]

array([8, 5, 5, 4, 2])

In [13]:
m[0:3,0:4]

array([[5, 7, 3, 5],
       [6, 9, 2, 5],
       [3, 8, 6, 8]])

In [14]:
m[::,:2]

array([[5, 7],
       [6, 9],
       [3, 8],
       [8, 5],
       [5, 2]])

In [3]:
import numpy as np
a = np.random.randint(10,size = (5,5))

In [4]:
a

array([[0, 0, 1, 0, 9],
       [6, 0, 7, 2, 5],
       [3, 5, 7, 7, 3],
       [4, 1, 8, 2, 2],
       [8, 2, 1, 7, 7]])

In [6]:
alt_a = a[:3,:2]

In [7]:
alt_a

array([[0, 0],
       [6, 0],
       [3, 5]])

In [8]:
alt_a[0,0] = 9999
alt_a[1,1] = 8888

In [9]:
alt_a

array([[9999,    0],
       [   6, 8888],
       [   3,    5]])

In [10]:
a

array([[9999,    0,    1,    0,    9],
       [   6, 8888,    7,    2,    5],
       [   3,    5,    7,    7,    3],
       [   4,    1,    8,    2,    2],
       [   8,    2,    1,    7,    7]])

In [ ]:
alt_b = 