In [1]:
import numpy as np

In [2]:
a = np.random.randint(10,size = 10)
a

array([6, 4, 0, 1, 9, 5, 4, 9, 1, 6])

In [3]:
a[0]

6

In [4]:
a[-1]

6

In [5]:
a[0] = 100

In [6]:
a

array([100,   4,   0,   1,   9,   5,   4,   9,   1,   6])

In [7]:
b = np.random.randint(10,size = (3,5))

In [8]:
b

array([[4, 3, 4, 9, 3],
       [3, 5, 0, 0, 3],
       [6, 0, 9, 3, 3]])

In [10]:
b[0][0]

4

In [11]:
b[0,0]

4

In [12]:
b[2,1]

0

In [14]:
b[2,2] = 10

In [15]:
b

array([[ 4,  3,  4,  9,  3],
       [ 3,  5,  0,  0,  3],
       [ 6,  0, 10,  3,  3]])

In [17]:
b[2,1]

0