In [1]:
import numpy as np

In [2]:
v = np.arange(1,30,3)
v

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [3]:
v[1]

4

In [4]:
[v[1],v[2],v[3],v[4]]

[4, 7, 10, 13]

In [6]:
al_getir = [1,3,5]

In [7]:
v

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [8]:
v[al_getir]

array([ 4, 10, 16])

In [9]:
#two dimentions


In [10]:
v = np.arange(0,9).reshape(3,3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#basit index ile fancy index

In [14]:
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
v[0,[1,2]]

array([1, 2])

In [17]:
#slice

In [19]:
v[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])