In [3]:
import numpy as np
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [4]:
v>5

array([False, False, False, False, False])

In [5]:
v>3

array([False, False, False,  True,  True])

In [6]:
v[v>3]

array([4, 5])

In [11]:
v[v<=3]

array([1, 2, 3])

In [12]:
v[v == 3]

array([3])

In [13]:
v[v != 3]

array([1, 2, 4, 5])

In [16]:
#mathematical operations

In [17]:
import numpy as np
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [18]:
v-1

array([0, 1, 2, 3, 4])

In [19]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [20]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [21]:
#ufunc

In [22]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [23]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [24]:
np.multiply(v,2)

array([ 2,  4,  6,  8, 10])

In [25]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [26]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [27]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [28]:
np.absolute(np.array([-3,-5]))

array([3, 5])

In [29]:
np.sin(360)

0.9589157234143065

In [30]:
np.cos(360)

-0.2836910914865273

In [31]:
v = np.arange(1,4)
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [32]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [33]:
#solving 2 unknown equation by numpy

In [34]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [35]:
a

array([[5, 1],
       [1, 3]])

In [36]:
b

array([12, 10])

In [38]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

In [42]:
x = np.array([[3,4],[2,3]])
y = np.array([13,22])

In [43]:
x

array([[3, 4],
       [2, 3]])

In [44]:
y

array([13, 22])

In [46]:
s = np.linalg.solve(a,b)

In [47]:
s

array([-49.,  40.])