In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,5,3])


In [3]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [8]:
v.sort() #this function has deadly side effect

In [9]:
v

array([1, 2, 3, 4, 5])

In [10]:
#two dimention

In [14]:
m = np.random.normal(20,5,(3,3))

In [15]:
m

array([[20.13404173, 17.40931914, 20.6352282 ],
       [ 9.45284032, 18.07794557, 11.49686695],
       [12.57392176, 26.05780216, 28.17387473]])

In [16]:
np.sort(m,axis = 1)

array([[17.40931914, 20.13404173, 20.6352282 ],
       [ 9.45284032, 11.49686695, 18.07794557],
       [12.57392176, 26.05780216, 28.17387473]])

In [18]:
np.sort(m,axis = 0)

array([[ 9.45284032, 17.40931914, 11.49686695],
       [12.57392176, 18.07794557, 20.6352282 ],
       [20.13404173, 26.05780216, 28.17387473]])