In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,99,99,3,2,1])

In [3]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [4]:
a,b,c = np.split(x,[3,5])

In [5]:
a

array([1, 2, 3])

In [6]:
b

array([99, 99])

In [7]:
c

array([3, 2, 1])

In [8]:
#two dimention

In [12]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [14]:
top,bottom = np.vsplit(m,[2])

In [15]:
top

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
bottom

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [18]:
h1,h2 = np.hsplit(m,[2])

In [19]:
h1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [20]:
h2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])