Değişken Dönüşümleri
--

In [1]:
import seaborn as sns
df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

0-1 Dönüşümü

In [2]:
from sklearn.preprocessing import LabelEncoder

lbe = LabelEncoder()

In [4]:
lbe.fit_transform(df["sex"])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [5]:
df["new_sex"] = lbe.fit_transform(df["sex"])
df.head()

total_bill   tip     sex smoker  day    time  size  new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        0
1       10.34  1.66    Male     No  Sun  Dinner     3        1
2       21.01  3.50    Male     No  Sun  Dinner     3        1
3       23.68  3.31    Male     No  Sun  Dinner     2        1
4       24.59  3.61  Female     No  Sun  Dinner     4        0

"1 ve diğerleri(0)" Dönüşümü

In [6]:
df.head()

total_bill   tip     sex smoker  day    time  size  new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        0
1       10.34  1.66    Male     No  Sun  Dinner     3        1
2       21.01  3.50    Male     No  Sun  Dinner     3        1
3       23.68  3.31    Male     No  Sun  Dinner     2        1
4       24.59  3.61  Female     No  Sun  Dinner     4        0

In [7]:
import numpy as np
df["new_day"] = np.where(df["day"].str.contains("Sun"),1,0)

In [8]:
df

total_bill   tip     sex smoker   day    time  size  new_sex  new_day
0         16.99  1.01  Female     No   Sun  Dinner     2        0        1
1         10.34  1.66    Male     No   Sun  Dinner     3        1        1
2         21.01  3.50    Male     No   Sun  Dinner     3        1        1
3         23.68  3.31    Male     No   Sun  Dinner     2        1        1
4         24.59  3.61  Female     No   Sun  Dinner     4        0        1
..          ...   ...     ...    ...   ...     ...   ...      ...      ...
239       29.03  5.92    Male     No   Sat  Dinner     3        1        0
240       27.18  2.00  Female    Yes   Sat  Dinner     2        0        0
241       22.67  2.00    Male    Yes   Sat  Dinner     2        1        0
242       17.82  1.75    Male     No   Sat  Dinner     2        1        0
243       18.78  3.00  Female     No  Thur  Dinner     2        0        0

[244 rows x 9 columns]

Çok Sınıflı Dönüşüm

In [9]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [10]:
lbe.fit_transform(df["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [1]:
import seaborn as sns
df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [2]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [3]:
lbe.fit_transform(df["sex"])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [4]:
df["new_sex"] = lbe.fit_transform(df["sex"])
df.head()

total_bill   tip     sex smoker  day    time  size  new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        0
1       10.34  1.66    Male     No  Sun  Dinner     3        1
2       21.01  3.50    Male     No  Sun  Dinner     3        1
3       23.68  3.31    Male     No  Sun  Dinner     2        1
4       24.59  3.61  Female     No  Sun  Dinner     4        0

In [5]:
import numpy as np
df["new_day"] = np.where(df["day"].str.contains("Sun"),1,0)
df.head()

total_bill   tip     sex smoker  day    time  size  new_sex  new_day
0       16.99  1.01  Female     No  Sun  Dinner     2        0        1
1       10.34  1.66    Male     No  Sun  Dinner     3        1        1
2       21.01  3.50    Male     No  Sun  Dinner     3        1        1
3       23.68  3.31    Male     No  Sun  Dinner     2        1        1
4       24.59  3.61  Female     No  Sun  Dinner     4        0        1

In [6]:
lbe = LabelEncoder()
lbe.fit_transform(df["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

One-Hot Dönüşümü ve Dummy Değişken Tuzağı
--

In [7]:
df.head()

total_bill   tip     sex smoker  day    time  size  new_sex  new_day
0       16.99  1.01  Female     No  Sun  Dinner     2        0        1
1       10.34  1.66    Male     No  Sun  Dinner     3        1        1
2       21.01  3.50    Male     No  Sun  Dinner     3        1        1
3       23.68  3.31    Male     No  Sun  Dinner     2        1        1
4       24.59  3.61  Female     No  Sun  Dinner     4        0        1

In [9]:
import pandas as pd
df_one_hot = pd.get_dummies(df,columns = ["sex"],prefix = ["sex"])

In [10]:
df_one_hot.head()

total_bill   tip smoker  day    time  size  new_sex  new_day  sex_Male  \
0       16.99  1.01     No  Sun  Dinner     2        0        1     False   
1       10.34  1.66     No  Sun  Dinner     3        1        1      True   
2       21.01  3.50     No  Sun  Dinner     3        1        1      True   
3       23.68  3.31     No  Sun  Dinner     2        1        1      True   
4       24.59  3.61     No  Sun  Dinner     4        0        1     False   

   sex_Female  
0        True  
1       False  
2       False  
3       False  
4        True

In [11]:
df_one_hot = pd.get_dummies(df,columns = ["day"],prefix = ["day"])
df_one_hot.head()

total_bill   tip     sex smoker    time  size  new_sex  new_day  day_Thur  \
0       16.99  1.01  Female     No  Dinner     2        0        1     False   
1       10.34  1.66    Male     No  Dinner     3        1        1     False   
2       21.01  3.50    Male     No  Dinner     3        1        1     False   
3       23.68  3.31    Male     No  Dinner     2        1        1     False   
4       24.59  3.61  Female     No  Dinner     4        0        1     False   

   day_Fri  day_Sat  day_Sun  
0    False    False     True  
1    False    False     True  
2    False    False     True  
3    False    False     True  
4    False    False     True

In [12]:
df_one_hot = pd.get_dummies(df,columns = ["smoker"],prefix = ["smoker"])
df_one_hot.head()

total_bill   tip     sex  day    time  size  new_sex  new_day  smoker_Yes  \
0       16.99  1.01  Female  Sun  Dinner     2        0        1       False   
1       10.34  1.66    Male  Sun  Dinner     3        1        1       False   
2       21.01  3.50    Male  Sun  Dinner     3        1        1       False   
3       23.68  3.31    Male  Sun  Dinner     2        1        1       False   
4       24.59  3.61  Female  Sun  Dinner     4        0        1       False   

   smoker_No  
0       True  
1       True  
2       True  
3       True  
4       True

In [13]:
df_one_hot = pd.get_dummies(df,columns = ["size"],prefix = ["size"])
df_one_hot.head()

total_bill   tip     sex smoker  day    time  new_sex  new_day  size_1  \
0       16.99  1.01  Female     No  Sun  Dinner        0        1   False   
1       10.34  1.66    Male     No  Sun  Dinner        1        1   False   
2       21.01  3.50    Male     No  Sun  Dinner        1        1   False   
3       23.68  3.31    Male     No  Sun  Dinner        1        1   False   
4       24.59  3.61  Female     No  Sun  Dinner        0        1   False   

   size_2  size_3  size_4  size_5  size_6  
0    True   False   False   False   False  
1   False    True   False   False   False  
2   False    True   False   False   False  
3    True   False   False   False   False  
4   False   False    True   False   False

In [1]:
import seaborn as sns
df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
lbe = LabelEncoder()
lbe.fit_transform(df["sex"])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [4]:
new_sex = lbe.fit_transform(df["sex"])

In [6]:
df["new_sex"] = lbe.fit_transform(df["sex"])
df.head()

total_bill   tip     sex smoker  day    time  size  new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        0
1       10.34  1.66    Male     No  Sun  Dinner     3        1
2       21.01  3.50    Male     No  Sun  Dinner     3        1
3       23.68  3.31    Male     No  Sun  Dinner     2        1
4       24.59  3.61  Female     No  Sun  Dinner     4        0

In [7]:
import numpy as np
df["new_day"] = np.where(df["day"].str.contains("Sun"),1,0)
df

total_bill   tip     sex smoker   day    time  size  new_sex  new_day
0         16.99  1.01  Female     No   Sun  Dinner     2        0        1
1         10.34  1.66    Male     No   Sun  Dinner     3        1        1
2         21.01  3.50    Male     No   Sun  Dinner     3        1        1
3         23.68  3.31    Male     No   Sun  Dinner     2        1        1
4         24.59  3.61  Female     No   Sun  Dinner     4        0        1
..          ...   ...     ...    ...   ...     ...   ...      ...      ...
239       29.03  5.92    Male     No   Sat  Dinner     3        1        0
240       27.18  2.00  Female    Yes   Sat  Dinner     2        0        0
241       22.67  2.00    Male    Yes   Sat  Dinner     2        1        0
242       17.82  1.75    Male     No   Sat  Dinner     2        1        0
243       18.78  3.00  Female     No  Thur  Dinner     2        0        0

[244 rows x 9 columns]

In [8]:
lbe = LabelEncoder()
lbe.fit_transform(df["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [9]:
import pandas as pd
df_one_hot = pd.get_dummies(df,columns = ["sex"],prefix = ["sex"])

In [10]:
df_one_hot

total_bill   tip smoker   day    time  size  new_sex  new_day  sex_Male  \
0         16.99  1.01     No   Sun  Dinner     2        0        1     False   
1         10.34  1.66     No   Sun  Dinner     3        1        1      True   
2         21.01  3.50     No   Sun  Dinner     3        1        1      True   
3         23.68  3.31     No   Sun  Dinner     2        1        1      True   
4         24.59  3.61     No   Sun  Dinner     4        0        1     False   
..          ...   ...    ...   ...     ...   ...      ...      ...       ...   
239       29.03  5.92     No   Sat  Dinner     3        1        0      True   
240       27.18  2.00    Yes   Sat  Dinner     2        0        0     False   
241       22.67  2.00    Yes   Sat  Dinner     2        1        0      True   
242       17.82  1.75     No   Sat  Dinner     2        1        0      True   
243       18.78  3.00     No  Thur  Dinner     2        0        0     False   

     sex_Female  
0          True  
1         False  
2         False  
3         False  
4          True  
..          ...  
239       False  
240        True  
241       False  
242       False  
243        True  

[244 rows x 10 columns]

In [14]:
df_one_hot = pd.get_dummies(df,columns = ["smoker"],prefix = ["smoker"])

In [15]:
df_one_hot.head()

total_bill   tip     sex  day    time  size  new_sex  new_day  smoker_Yes  \
0       16.99  1.01  Female  Sun  Dinner     2        0        1       False   
1       10.34  1.66    Male  Sun  Dinner     3        1        1       False   
2       21.01  3.50    Male  Sun  Dinner     3        1        1       False   
3       23.68  3.31    Male  Sun  Dinner     2        1        1       False   
4       24.59  3.61  Female  Sun  Dinner     4        0        1       False   

   smoker_No  
0       True  
1       True  
2       True  
3       True  
4       True