Veri Standardizasyonu Ve Değişken Dönüşümü
--

Standartlaştırma

In [1]:
import numpy as np
import pandas as pd

V1 = np.array([1,3,6,5,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])

df = pd.DataFrame(
{
    "V1":V1,
    "V2":V2,
    "V3":V3
})

df = df.astype(float)
df.head()

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [2]:
from sklearn import preprocessing

In [3]:
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [4]:
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

Normalizasyon
--

In [5]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

Min-Max Dönüşümü
--

In [6]:
scaler = preprocessing.MinMaxScaler(feature_range = (10,20)) 

In [7]:
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

Binarize Dönüşümü
--

In [8]:
binarizer = preprocessing.Binarizer(threshold = 5).fit(df)

In [9]:
binarizer.transform(df)

array([[0., 1., 1.],
       [0., 1., 1.],
       [1., 0., 0.],
       [0., 1., 1.],
       [1., 1., 1.]])

0-1 Dönüşümü
--

In [11]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()

df_l = df.copy()

In [12]:
df_l.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [14]:
df_l["new_sex"] = df_l["sex"].cat.codes
df_l.head()

total_bill   tip     sex smoker  day    time  size  new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        1
1       10.34  1.66    Male     No  Sun  Dinner     3        0
2       21.01  3.50    Male     No  Sun  Dinner     3        0
3       23.68  3.31    Male     No  Sun  Dinner     2        0
4       24.59  3.61  Female     No  Sun  Dinner     4        1

In [16]:
from sklearn.preprocessing import LabelEncoder
lbe = preprocessing.LabelEncoder()

In [18]:
df_l["newest_sex"] = lbe.fit_transform(df_l["sex"])
df_l.head()

total_bill   tip     sex smoker  day    time  size  new_sex  newest_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        1           0
1       10.34  1.66    Male     No  Sun  Dinner     3        0           1
2       21.01  3.50    Male     No  Sun  Dinner     3        0           1
3       23.68  3.31    Male     No  Sun  Dinner     2        0           1
4       24.59  3.61  Female     No  Sun  Dinner     4        1           0

"1 Ve Diğerleri(0)" Dönüşümü
--

In [19]:
import numpy as np
df_l["new_day"] = np.where(df_l["day"].str.contains("Sun"),1,0)

In [21]:
df_l.head(20)

total_bill   tip     sex smoker  day    time  size  new_sex  newest_sex  \
0        16.99  1.01  Female     No  Sun  Dinner     2        1           0   
1        10.34  1.66    Male     No  Sun  Dinner     3        0           1   
2        21.01  3.50    Male     No  Sun  Dinner     3        0           1   
3        23.68  3.31    Male     No  Sun  Dinner     2        0           1   
4        24.59  3.61  Female     No  Sun  Dinner     4        1           0   
5        25.29  4.71    Male     No  Sun  Dinner     4        0           1   
6         8.77  2.00    Male     No  Sun  Dinner     2        0           1   
7        26.88  3.12    Male     No  Sun  Dinner     4        0           1   
8        15.04  1.96    Male     No  Sun  Dinner     2        0           1   
9        14.78  3.23    Male     No  Sun  Dinner     2        0           1   
10       10.27  1.71    Male     No  Sun  Dinner     2        0           1   
11       35.26  5.00  Female     No  Sun  Dinner     4        1           0   
12       15.42  1.57    Male     No  Sun  Dinner     2        0           1   
13       18.43  3.00    Male     No  Sun  Dinner     4        0           1   
14       14.83  3.02  Female     No  Sun  Dinner     2        1           0   
15       21.58  3.92    Male     No  Sun  Dinner     2        0           1   
16       10.33  1.67  Female     No  Sun  Dinner     3        1           0   
17       16.29  3.71    Male     No  Sun  Dinner     3        0           1   
18       16.97  3.50  Female     No  Sun  Dinner     3        1           0   
19       20.65  3.35    Male     No  Sat  Dinner     3        0           1   

    new_day  
0         1  
1         1  
2         1  
3         1  
4         1  
5         1  
6         1  
7         1  
8         1  
9         1  
10        1  
11        1  
12        1  
13        1  
14        1  
15        1  
16        1  
17        1  
18        1  
19        0

Çok sınıflı Dönüşüm
--

In [22]:
lbe = LabelEncoder()

In [23]:
df_l["newest_day"] = lbe.fit_transform(df_l["day"])
df_l.head()

total_bill   tip     sex smoker  day    time  size  new_sex  newest_sex  \
0       16.99  1.01  Female     No  Sun  Dinner     2        1           0   
1       10.34  1.66    Male     No  Sun  Dinner     3        0           1   
2       21.01  3.50    Male     No  Sun  Dinner     3        0           1   
3       23.68  3.31    Male     No  Sun  Dinner     2        0           1   
4       24.59  3.61  Female     No  Sun  Dinner     4        1           0   

   new_day  newest_day  
0        1           2  
1        1           2  
2        1           2  
3        1           2  
4        1           2

One-Hot Dönüşümü ve Dummy Değişken Tuzağı
--

In [24]:
df_one_hot = df.copy()

In [25]:
pd.get_dummies(df_one_hot,columns = ["sex"],prefix = ["sex"]).head()

total_bill   tip smoker  day    time  size  newest_sex  sex_Male  \
0       16.99  1.01     No  Sun  Dinner     2           0     False   
1       10.34  1.66     No  Sun  Dinner     3           1      True   
2       21.01  3.50     No  Sun  Dinner     3           1      True   
3       23.68  3.31     No  Sun  Dinner     2           1      True   
4       24.59  3.61     No  Sun  Dinner     4           0     False   

   sex_Female  
0        True  
1       False  
2       False  
3       False  
4        True

In [26]:
pd.get_dummies(df_one_hot,columns = ["day"],prefix = ["day"]).head()

total_bill   tip     sex smoker    time  size  newest_sex  day_Thur  \
0       16.99  1.01  Female     No  Dinner     2           0     False   
1       10.34  1.66    Male     No  Dinner     3           1     False   
2       21.01  3.50    Male     No  Dinner     3           1     False   
3       23.68  3.31    Male     No  Dinner     2           1     False   
4       24.59  3.61  Female     No  Dinner     4           0     False   

   day_Fri  day_Sat  day_Sun  
0    False    False     True  
1    False    False     True  
2    False    False     True  
3    False    False     True  
4    False    False     True

Sürekli Değişkeni Kategorik Değişkene Çevirme
--

In [27]:
df.head()

total_bill   tip     sex smoker  day    time  size  newest_sex
0       16.99  1.01  Female     No  Sun  Dinner     2           0
1       10.34  1.66    Male     No  Sun  Dinner     3           1
2       21.01  3.50    Male     No  Sun  Dinner     3           1
3       23.68  3.31    Male     No  Sun  Dinner     2           1
4       24.59  3.61  Female     No  Sun  Dinner     4           0

In [32]:
dff = df.select_dtypes(include = ["float64","int64"])
est = preprocessing.KBinsDiscretizer(n_bins = [3,2,2],encode = "ordinal",strategy = "quantile").fit(dff)

In [33]:
est.transform(dff)[0:10]

array([[1., 0., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

Değişkeni İndex'e İndex'i değişkene Çevirme
--

In [1]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()

df_l = df.copy()

In [2]:
df["yeni_değişken"] = df.index

In [3]:
df

total_bill   tip     sex smoker   day    time  size  yeni_değişken
0         16.99  1.01  Female     No   Sun  Dinner     2              0
1         10.34  1.66    Male     No   Sun  Dinner     3              1
2         21.01  3.50    Male     No   Sun  Dinner     3              2
3         23.68  3.31    Male     No   Sun  Dinner     2              3
4         24.59  3.61  Female     No   Sun  Dinner     4              4
..          ...   ...     ...    ...   ...     ...   ...            ...
239       29.03  5.92    Male     No   Sat  Dinner     3            239
240       27.18  2.00  Female    Yes   Sat  Dinner     2            240
241       22.67  2.00    Male    Yes   Sat  Dinner     2            241
242       17.82  1.75    Male     No   Sat  Dinner     2            242
243       18.78  3.00  Female     No  Thur  Dinner     2            243

[244 rows x 8 columns]

In [4]:
df["yeni_değişken"] = df["yeni_değişken"] + 10

In [5]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_değişken
0       16.99  1.01  Female     No  Sun  Dinner     2             10
1       10.34  1.66    Male     No  Sun  Dinner     3             11
2       21.01  3.50    Male     No  Sun  Dinner     3             12
3       23.68  3.31    Male     No  Sun  Dinner     2             13
4       24.59  3.61  Female     No  Sun  Dinner     4             14

In [6]:
df.index = df["yeni_değişken"]

In [7]:
df

total_bill   tip     sex smoker   day    time  size  \
yeni_değişken                                                        
10                  16.99  1.01  Female     No   Sun  Dinner     2   
11                  10.34  1.66    Male     No   Sun  Dinner     3   
12                  21.01  3.50    Male     No   Sun  Dinner     3   
13                  23.68  3.31    Male     No   Sun  Dinner     2   
14                  24.59  3.61  Female     No   Sun  Dinner     4   
...                   ...   ...     ...    ...   ...     ...   ...   
249                 29.03  5.92    Male     No   Sat  Dinner     3   
250                 27.18  2.00  Female    Yes   Sat  Dinner     2   
251                 22.67  2.00    Male    Yes   Sat  Dinner     2   
252                 17.82  1.75    Male     No   Sat  Dinner     2   
253                 18.78  3.00  Female     No  Thur  Dinner     2   

               yeni_değişken  
yeni_değişken                 
10                        10  
11                        11  
12                        12  
13                        13  
14                        14  
...                      ...  
249                      249  
250                      250  
251                      251  
252                      252  
253                      253  

[244 rows x 8 columns]